services:
  postgres:
    image: postgres:11-alpine
    command: ["postgres", "-c", "log_min_duration_statement=1000", "-c", "log_destination=stderr"]
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres