spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRESQL_ADDON_HOST:localhost}:${POSTGRESQL_ADDON_PORT:5432}/${POSTGRESQL_ADDON_DB:audace}
    username: ${POSTGRESQL_ADDON_USER:audace}
    password: ${POSTGRESQL_ADDON_PASSWORD:audace}
    initialSize: 2
    maxSize: 10
  liquibase:
    change-log: classpath:db/changelog/db-changelog.sql
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST:localhost}:${POSTGRESQL_ADDON_PORT:5432}/${POSTGRESQL_ADDON_DB:audace}
    user: ${POSTGRESQL_ADDON_USER:audace}
    password: ${POSTGRESQL_ADDON_PASSWORD:audace}
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
    liquibase: INFO