name: Release with Gradle

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (Major, Minor, Patch)'
        required: true
        default: 'Minor'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Release
        run: ./gradlew release -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR}  -Prelease.versionIncrementer=increment${RELEASE_TYPE}
      - name: Merge in production
        run: git checkout production; git merge main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TYPE: ${{ github.event.inputs.release-version || 'Minor' }}
